---
- hosts: "{{host_play}}"
  become: yes
  vars_prompt:
    - name: host_play
      prompt: What is your host?
      private: no
    - name: server 
      prompt: What is your server (example:45.155.207.74)?
      private: no
    - name: TLSConnect
      prompt: What is TLSConnect (example:psk)?
      private: no
    - name: TLSAccept
      prompt: What is TLSAccept (example:psk)?
      private: no
    - name: TLSPSKIdentity 
      prompt: What is TLSPSKIdentity (example:PSK0014)?
      private: no
    - name: TLSPSKFile
      prompt: What will be the path to TLSPSKFile (example:/etc/zabbix/zabbix_agentd.psk)?
      private: no

  tasks:
    - name: Check for file presence
      ansible.builtin.script: Created_PSK.sh --some-argument 1234
      register: script_out
      become: true
      tags: Check for file presence

    - name: "print script output"
      debug:
        msg: "{{ script_out }}"
      become: true

    - name: edit_hostname
      lineinfile: dest=/etc/zabbix/zabbix_agentd.conf regexp='^Hostname=' insertbefore=BOF line='Hostname={{ ansible_hostname }}'
      become: true
      tags: edit_hostname

    - name: edit_server
      lineinfile: dest=/etc/zabbix/zabbix_agentd.conf regexp='^Server='  line='Server={{server}}'
      become: true
      tags: edit_server

    - name: TLSConnect=psk
      lineinfile: dest=/etc/zabbix/zabbix_agentd.conf insertafter="^#" line="TLSConnect={{TLSConnect}}"
      become: true
      tags: TLSConnect=psk

    - name: TLSAccept=psk
      lineinfile: dest=/etc/zabbix/zabbix_agentd.conf insertafter="^TLSConnect" line="TLSAccept={{TLSAccept}}"
      become: true
      tags: TLSAccept=psk

    - name: TLSPSKIdentity=PSK0014
      lineinfile: dest=/etc/zabbix/zabbix_agentd.conf insertafter="^TLSAccept" line="TLSPSKIdentity={{TLSPSKIdentity}}"
      become: true
      tags: TLSPSKIdentity=PSK0014

    - name: TLSPSKFile=/etc/zabbix/zabbix_agentd.psk
      lineinfile: dest=/etc/zabbix/zabbix_agentd.conf insertafter="^TLSPSKIdentity" line="TLSPSKFile={{TLSPSKFile}}"
      become: true
      tags: TLSPSKFile=/etc/zabbix/zabbix_agentd.psk

    - name: restart zabbix
      service: name=zabbix-agent state=restarted
      become: true
      tags: restart_zabbix

   
    - name: Print Zabbix PSK
      shell: cat /etc/zabbix/zabbix_agentd.psk
      register: results

    - debug:
        var: results.stdout
